---
# task file for installing and configuring cobbler on CentOS

- name: install related packages
  yum: name={{ item }} state=present
  with_items:
    - epel
    - dhcp
    - xinetd
    - tftp
    - tftp-server
    - cobbler
    - pykickstart
    - httpd
    - fence-agents

- name: dhcpd configuration file
  template: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf


- name: start and enable service
  service: name={{ item }} state=started enabled=yes
  with_items::
    - dhcpd
    - xinetd
    - httpd
    - cobblerd


