---
# task file for installing and configuring cobbler on CentOS

- name: install epel repo
  yum: name=epel-release state=present
  become: true

- name: install related packages
  yum: name={{ item }} state=present
  with_items:
    - dhcp
    - xinetd
    - tftp
    - tftp-server
    - cobbler
    - pykickstart
    - httpd
    - fence-agents
  become: true

- name: generate crypted password
  shell: openssl passwd -1 {{ cobbler_default_password }}
  register: cobbler_default_password_crypted

- name: template /etc/cobbler/settings
  template: src=etc/cobbler/settings.j2 dest=/etc/cobbler/settings
  become: true

#- name: dhcpd configuration file
#  template: src=dhcpd.conf dest=/etc/dhcp/dhcpd.conf
#

#- name: start and enable service
#  service: name={{ item }} state=started enabled=yes
#  with_items::
#    - dhcpd
#    - xinetd
#    - httpd
#    - cobblerd


